[pytest]
;addopts = -v --tb=short
markers =
    smoke: smoke tests
    regression: regression tests

;addopts = -v --tb=short --html=reports/report.html --self-contained-html

addopts =
    -v --tb=short
    --alluredir=reports/allure-results

testpaths = tests
python_files = test_*.py
log_cli = true