[pytest]
;addopts = -v --tb=short
markers =
    smoke: smoke tests
    regression: regression tests

;addopts = -v --tb=short --html=reports/report.html --self-contained-html

addopts = -v --tb=short
testpaths = tests
python_files = test_*.py
